require:
  - rubocop-minitest
  - rubocop-performance
  - rubocop-rake

inherit_from:
  - .rubocop_todo.yml

# Set our base version of ruby and enable all cops.
AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable

# Turn this off for certain files where we have extra documentation
# towards the end of the file, after a block of private methods.
Lint/UselessAccessModifier:
  Exclude:
    - 'lib/cff/model.rb'
    - 'lib/cff/reference.rb'

# I think 'has_key?' looks better than 'key?'.
Style/PreferredHashMethods:
  EnforcedStyle: verbose

# Allow a non-standard error type.
Style/RaiseArgs:
  AllowedCompactTypes:
    - ValidationError
    - CFF::ValidationError

# Enforce empty lines at the beginning of classes.
Layout/EmptyLinesAroundClassBody:
  EnforcedStyle: beginning_only

# Allow empty lines, or not, around module bodies. I like a line at the
# beginning, but not the end, but this is not an option in RuboCop.
Layout/EmptyLinesAroundModuleBody:
  Enabled: false

# Allow long lines in the tests.
Layout/LineLength:
  Exclude:
    - 'test/**/*.rb'

# Force ruby19 style hash keys, but be consistent within a hash.
Style/HashSyntax:
  EnforcedStyle: ruby19_no_mixed_keys

# Enforce %w notation in the library code, but be less strict in tests.
Style/WordArray:
  Enabled: false

# Ignore ABC failures in the tests.
Metrics/AbcSize:
  Exclude:
    - 'test/**/*.rb'

# Ignore block length failures in the tests.
Metrics/BlockLength:
  Exclude:
    - 'cff.gemspec'
    - 'test/**/*.rb'

# Set a more reasonable method length and ignore failures in the tests.
Metrics/MethodLength:
  Max: 20
  Exclude:
    - 'test/**/*.rb'

# Set a more reasonable class length and ignore failures in the tests.
Metrics/ClassLength:
  Max: 150
  Exclude:
    - 'test/**/*.rb'
